version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: express_server
    environment:
      DATABASE_URL: "postgresql://watRoot:wat123546@210.246.215.231:5432/wat"
    ports:
      - '5000:5000'
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - '3000:3000'
    environment:
      REACT_APP_BACKEND_URL: "http://express_server:5000"
    networks:
      - app_network
    stdin_open: true
    tty: true

networks:
  app_network:
    driver: bridge
