version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: express_server
    environment:
      DATABASE_URL: "postgresql://watRoot:wat123546@210.246.215.231:5432/wat"
    ports:
      - '5000:5000'
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - '3000:3000'
    environment:
      REACT_APP_BACKEND_URL: "http://express_server:5000"
    networks:
      - app_network
    stdin_open: true
    tty: true

  backup-service:
    build:
      context: ./backup
    container_name: pg_backup_service
    environment:
      PG_USER: "watRoot"
      PG_PASSWORD: "wat123546"
      PG_HOST: "210.246.215.231"
      PG_PORT: 5432
      PG_DATABASE: "wat"
      BACKUP_DIR: "/app/backups"
      GOOGLE_DRIVE_FOLDER_ID: "1vmf26KBX70G9xaFOeip0ZPwEBXFYv9Mo"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/credentials.json"  # ชี้ไปยังไฟล์ credentials
    volumes:
      - ./backups:/app/backups
      - /root/dtc/credentials.json:/app/credentials/credentials.json  # Mount ไฟล์ credentials.json
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
